"""empty message

Revision ID: 1543aafc495e
Revises: 437ee4b22726
Create Date: 2023-08-23 12:11:21.120288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1543aafc495e'
down_revision: Union[str, None] = '437ee4b22726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('warning_name_unique', 'warning_status', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('warning_name_unique', 'warning_status', type_='unique')
    # ### end Alembic commands ###
