"""empty message

Revision ID: 2dece1542da6
Revises: 1543aafc495e
Create Date: 2023-09-14 12:32:01.537183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2dece1542da6"
down_revision: Union[str, None] = "1543aafc495e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "warnings", sa.Column("created", sa.DateTime(), server_default="NOW()")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("warnings", "created")
    # ### end Alembic commands ###
