"""empty message

Revision ID: 437ee4b22726
Revises: d76f8cfa35e6
Create Date: 2023-08-23 12:03:05.681464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '437ee4b22726'
down_revision: Union[str, None] = 'd76f8cfa35e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('warning_status_warning_id_fkey', 'warning_status', type_='foreignkey')
    op.drop_column('warning_status', 'warning_id')
    op.drop_column('warning_status', 'message')
    op.drop_column('warning_status', 'datetime')
    op.add_column('warnings', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warnings', 'warning_status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warnings', type_='foreignkey')
    op.drop_column('warnings', 'status_id')
    op.add_column('warning_status', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('warning_status', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('warning_status', sa.Column('warning_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('warning_status_warning_id_fkey', 'warning_status', 'warnings', ['warning_id'], ['id'])
    # ### end Alembic commands ###
