"""empty message

Revision ID: 83bff95e1bfa
Revises: e495c85e6006
Create Date: 2023-08-20 19:33:33.995368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bff95e1bfa'
down_revision: Union[str, None] = 'e495c85e6006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('name_unique', 'settings', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('name_unique', 'settings', type_='unique')
    # ### end Alembic commands ###
