"""empty message

Revision ID: 9db5ad4bdfb2
Revises: 9a42ac495456
Create Date: 2023-08-23 11:41:33.070068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db5ad4bdfb2'
down_revision: Union[str, None] = '9a42ac495456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warnings', sa.Column('success_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warnings', 'success_message')
    # ### end Alembic commands ###
