"""empty message

Revision ID: af11933bc06d
Revises: d73ea7514340
Create Date: 2023-08-20 16:54:41.710440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af11933bc06d'
down_revision: Union[str, None] = 'd73ea7514340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warnings', sa.Column('last_notification', sa.DateTime(), nullable=True))
    op.add_column('warnings', sa.Column('repeat_days', sa.Integer(), server_default='0', nullable=True))
    op.add_column('warnings', sa.Column('repeat_hours', sa.Integer(), server_default='0', nullable=True))
    op.add_column('warnings', sa.Column('repeat_minutes', sa.Integer(), server_default='0', nullable=True))
    op.add_column('warnings', sa.Column('repeat_seconds', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warnings', 'repeat_seconds')
    op.drop_column('warnings', 'repeat_minutes')
    op.drop_column('warnings', 'repeat_hours')
    op.drop_column('warnings', 'repeat_days')
    op.drop_column('warnings', 'last_notification')
    # ### end Alembic commands ###
