"""empty message

Revision ID: d73ea7514340
Revises: 837015d1e827
Create Date: 2023-08-20 16:27:24.876257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73ea7514340'
down_revision: Union[str, None] = '837015d1e827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warnings', sa.Column('last_success', sa.DateTime(), nullable=True))
    op.add_column('warnings', sa.Column('wait_days', sa.Integer(), server_default='0', nullable=True))
    op.add_column('warnings', sa.Column('wait_hours', sa.Integer(), server_default='0', nullable=True))
    op.add_column('warnings', sa.Column('wait_minutes', sa.Integer(), server_default='0', nullable=True))
    op.add_column('warnings', sa.Column('wait_seconds', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warnings', 'wait_seconds')
    op.drop_column('warnings', 'wait_minutes')
    op.drop_column('warnings', 'wait_hours')
    op.drop_column('warnings', 'wait_days')
    op.drop_column('warnings', 'last_success')
    # ### end Alembic commands ###
