"""empty message

Revision ID: f8fac36f4f74
Revises: af11933bc06d
Create Date: 2023-08-20 17:46:23.405720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fac36f4f74'
down_revision: Union[str, None] = 'af11933bc06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipients', sa.Column('warning_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipients', 'warnings', ['warning_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipients', type_='foreignkey')
    op.drop_column('recipients', 'warning_id')
    # ### end Alembic commands ###
